POST http://localhost:9090/omsOrder/getByIds
Content-Type: application/json

{
  "idList": [30,20]
}

###

GET http://localhost:9090/omsOrder/getById/12
Accept: application/json

###
POST http://localhost:9090/omsOrder/list
Accept: application/json
Content-Type: application/json

{

}

###

POST http://localhost:9090/omsOrder/get
Content-Type: application/json

{
  "memberUsername": "test"
}

###
GET http://localhost:9090/omsOrder/getById/20
Accept: application/json

###
POST http://localhost:9090/omsOrder/updateById
Content-Type: application/json

{
  "memberUsername": "test1",
  "id": 12
}

###
GET http://localhost:9090/omsOrder/getById/121670708295306001
Accept: application/json

###
POST http://localhost:9090/omsOrder/deleteById
Content-Type: application/json

{
  "id": 12
}

###
POST http://localhost:9090/omsOrder/insert
Content-Type: application/json

{
  "memberId": 1,
  "couponId": 2,
  "orderSn": "201809150101000001",
  "createTime": "2020-07-04 16:03:49",
  "memberUsername": "test1",
  "totalAmount": 18732.00,
  "payAmount": 16377.75,
  "freightAmount": 20.00,
  "promotionAmount": 2344.25,
  "integrationAmount": 0.00,
  "couponAmount": 10.00,
  "discountAmount": 10.00,
  "payType": 0,
  "sourceType": 1,
  "status": 4,
  "orderType": 0,
  "deliveryCompany": "",
  "deliverySn": "",
  "autoConfirmDay": 15,
  "integration": 13284,
  "growth": 13284,
  "promotionInfo": "单品促销,打折优惠：满3件，打7.50折,满减优惠：满1000.00元，减120.00元,满减优惠：满1000.00元，减120.00元,无优惠",
  "billType": null,
  "billHeader": null,
  "billContent": null,
  "billReceiverPhone": null,
  "billReceiverEmail": null,
  "receiverName": "大梨",
  "receiverPhone": "18033441849",
  "receiverPostCode": "518000",
  "receiverProvince": "江苏省",
  "receiverCity": "常州市",
  "receiverRegion": "天宁区",
  "receiverDetailAddress": "东晓街道",
  "note": "111",
  "confirmStatus": 0,
  "deleteStatus": 0,
  "useIntegration": null,
  "paymentTime": null,
  "deliveryTime": null,
  "receiveTime": null,
  "commentTime": null
}

###
GET http://localhost:9090/omsOrder/export


###
POST http://localhost:9090/cmsHelpCategory/list
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:9090/cmsSubject/list
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:9090/test/list
Accept: application/json
Content-Type: application/json

{}
###
POST http://localhost:9090/umsAdmin/list
Accept: application/json
Content-Type: application/json

{}
